# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2.2', '3.3.0']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create .env file
        run : |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Execute docker-compose
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Run tests
        run: docker-compose exec -T app "bundle exec rspec /usr/src/app/spec/actions/projects/create_spec.rb"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down